### ISSUE TITLE
SlimeProperties behaving incorrectly

### ISSUE THREAD

**Issue by shivasuc** [RealGatt/SkSWM#1]
Issue: When creating a new slime world, the console gets errors saying that a property was expeting a centain type, and then shows a  value that isn't the type it expects, however in code, the types are the same.

![image](https://user-images.githubusercontent.com/62576532/87701979-27b9b280-c76f-11ea-9948-3e3962a33e47.png)

Code used:
```     
        set {_props} to new slime world property map
	set difficulty of {_props} to "normal"
	set spawn x of {_props} to 0.5
	set spawn y of {_props} to 63
	set spawn z of {_props} to 0.5
	set {_world} to slime world named "sb_%{_id}%" from file using properties {_props}
	load slime world {_world}```

**Comment by RealGatt** [comment]
Will look into it.

**Comment by RealGatt** [comment]
What version of SlimeWorldManager are you using?

**Comment by RealGatt** [comment]
Issue found and located. Somehow deleted some breaks in a switch case before shipping. Posting update soon

**Comment by RealGatt** [comment]
Fixed.

https://forums.skunity.com/resources/skswm-slimeworldmanager-addon-for-skript.1028/update?update=2631

**Comment by Padlick** [comment]
It still behaves incorrect. 
When you do 

`set {_SWMsettings} to new slime world property map`
`set spawn x of {_SWMsettings} to 0`
`set spawn y of {_SWMsettings} to 64`
`set spawn z of {_SWMsettings} to 0`

Your Addon returns 
`[Skript] spawnX expected a Integer, but got 0`
`[Skript] spawnY expected a Integer, but got 64`
`[Skript] spawnZ expected a Integer, but got 0`

(0.0 and 64.0 also doesn't work)

**Comment by RealGatt** [comment]
Seems like Skript gives Integers as Numbers regardless. Fixed in newest release
