### ISSUE TITLE
unlock slime world throws ClassCastException

### ISSUE THREAD

**Issue by Padlick** [RealGatt/SkSWM#2]
When you use the effect 

`unlock slime world "padlick" in file`

Skript throws a stack trace with an ClassCastException:
https://pastebin.com/8umMVwGC

The slime world "padlick" was created earlier using this lines of code:
https://pastebin.com/J5K05x8F

SkSWM: v1.1.1
Skript: 2.5 beta-5
paper: 1.15.2 git-Paper-379

**Comment by RealGatt** [comment]
Fixed.

**Comment by RealGatt** [comment]
https://forums.skunity.com/resources/skswm-slimeworldmanager-addon-for-skript.1028/update?update=2638
